# Generated by Django 4.2.2 on 2023-06-23 16:04

from django.db import migrations, models
import validators.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[validators.validators.minimum_two_char_validator])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(validators=[validators.validators.age_validator])),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
